### ISSUE TITLE
Backwards compatibility issue

### ISSUE THREAD

**Issue by migore** [felipecsl/wombat#53]
I upgraded to wombat 2.5.0 and my script stopped working. The following script works on wombat 2.4.0 but fails in 2.5.0. I took some code out in order to isolate the problem.
```ruby
require 'wombat'

result = Wombat.crawl do
	base_url "http://www.icy-veins.com/" 
	path "heroes/hero-guides"

	heroes  "css=.page_content .nav_content_block_entry_heroes_hero", :iterator do
		name "xpath=."
		builds "xpath=./a", :follow do
			title "css=h1"
		end
	end
end
```

I get the following error:

```
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/follow.rb:10:in `block (2 levels) in locate': undefined method `mechanize_page' for #<Nokogiri::XML::Element:0x007ffbe44e8760> (NoMethodError)
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/follow.rb:9:in `flat_map'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/follow.rb:9:in `block in locate'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:18:in `locate'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/follow.rb:8:in `locate'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:35:in `block (2 levels) in filter_properties'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:35:in `map'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:35:in `block in filter_properties'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:32:in `tap'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:32:in `filter_properties'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/iterator.rb:11:in `block (2 levels) in locate'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/iterator.rb:10:in `flat_map'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/iterator.rb:10:in `block in locate'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:18:in `locate'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/iterator.rb:9:in `locate'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:35:in `block (2 levels) in filter_properties'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:35:in `map'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:35:in `block in filter_properties'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:32:in `tap'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:32:in `filter_properties'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/property_group.rb:9:in `block in locate'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/base.rb:18:in `locate'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/property/locators/property_group.rb:8:in `locate'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/processing/parser.rb:43:in `parse'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat/crawler.rb:30:in `crawl'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/wombat-2.5.0/lib/wombat.rb:13:in `crawl'
	from crawler.rb:4:in `<main>'
```

**Comment by felipecsl** [comment]
Thanks for the report Ygor :)

**Comment by vanderhoorn** [comment]
Running into the same issue. Is it possible to create a patch release for this?

Thanks in advance!

**Comment by vanderhoorn** [comment]
Is it possible to create a patch release (e.g. 2.5.1) for this issue?

Thanks in advance for your time.

**Comment by felipecsl** [comment]
Done, released as 2.5.1 https://rubygems.org/gems/wombat

**Comment by vanderhoorn** [comment]
Awesome, thanks!
